version: '3.7'
services:
  mongo:
    networks:
      - shared
    image: mongo:4.1
    restart: always
    volumes:
      - mdb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  formio:
    container_name: formio_builder
    build: ./
    restart: always
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      ROOT_EMAIL: admin@example.com
      ROOT_PASSWORD: CHANGEME
    stdin_open: true  # -i
    tty: true         # -t

volumes:
  mdb-data: